Count failures

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -151,11 +151,21 @@ jobs:
       - name: Run tests
         run: |
           set +e
+          failed_count=0
+          mkdir logs
           for i in {1..20}; do
             cargo test > log
             rc=$?
+            echo "Attempt #$i --> $rc"
             if [ "$rc" != '0' ]; then
-              cat log
-              exit "$rc"
+              ((failed_count++))
+              mv log logs/$(date +%s).log
             fi
           done
+
+          if [ "$failed_count" != 0 ]; then
+            cat logs/*.log
+            echo "::error ::$failed_count out of 20 attempts failed."
+            exit 1
+          fi
+
